[package]
name = "bootmgr-rs-ratatui"
version = "0.5.0"
edition = "2024"

[dependencies]
bootmgr-rs-core = { version = "0.1.0", path = "../bootmgr-rs-core" }
log = "0.4.27"
ratatui-core = "0.1.0-alpha.6"
ratatui-widgets = "0.3.0-alpha.5"
smallvec = "1.15.1"
thiserror = { version = "2.0.12", default-features = false }
uefi = { version = "0.35.0", features = ["alloc"] }

[features]
default = ["editor"]
editor = []

[lints]
workspace = true
