[workspace]
members = [
    "bootmgr-rs",
    "bootmgr-rs-tests",
    "fuzz",
    "xtask",
]
default-members = [
    "bootmgr-rs",
    "bootmgr-rs-tests",
]
resolver = "3"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = "warn"
mod_module_files = "warn"
missing_docs_in_private_items = "warn"
