import { Theme } from "theme.slint";

export component BootList {
    in-out property <int> listIdx;
    in-out property <int> timeout;
    in property <length> spacing;
    in property <length> itemWidth;
    in property <int> count: 0;

    callback move-right();
    callback move-left();

    callback tryboot(int);

    move-right => {
        root.listIdx = min(root.listIdx + 1, root.count - 1);
    }

    move-left => {
        root.listIdx = max(root.listIdx - 1, 0);
    }

    forward-focus: focus-scope;
    height: Theme.size-big;
    preferred-width: 100%;

    focus-scope := FocusScope {
        key-pressed(event) => {
            timeout = -1;
            if (event.text == Key.LeftArrow) {
                root.move-left();
                return accept;
            }
            if (event.text == Key.RightArrow) {
                root.move-right();
                return accept;
            }
            if (event.text == Key.Return) {
                root.tryboot(root.listIdx);
                return accept;
            }
            return accept;
        }
    }

    Timer {
        interval: 1000ms;
        running: true;
        triggered() => {
            if timeout == 0 {
                root.tryboot(root.listIdx);
            } else if timeout > 0 {
                timeout -= 1;
            }
        }
    }

    Rectangle {
        clip: true;

        Rectangle {
            property <length> viewport-x: ((root.width - Theme.size-big) / 2) - root.listIdx * (root.itemWidth + root.spacing);
            animate viewport-x {
                duration: Theme.duration-fast;
                easing: ease-in;
            }
            
            property <length> swipe-offset: 0;
            x: self.viewport-x + swipe-offset;
            width: inner-layout.preferred-width;

            inner-layout := HorizontalLayout {
                spacing <=> root.spacing;

                @children
            }
        }
    }
}
