// SPDX-FileCopyrightText: 2025 some100 <ootinnyoo@outlook.com>
// SPDX-License-Identifier: MIT

import { Theme } from "theme.slint";
import { TitleLabel } from "title_label.slint";

export component Card inherits Rectangle {
    in property <string> title: "title";
    in property <bool> is-selected: false;
    in property <image> image-source <=> image.source;
    in property <color> fg;
    in property <color> highlight-bg;
    in property <color> highlight-fg;

    private property <length> spacing: Theme.spacing-medium;
    private property <length> title-spacing: Theme.spacing-medium;
    private property <length> title-area-height: Theme.size-small;

    border-radius: Theme.radius-regular;
    background: highlight-bg;
    width: Theme.size-medium;
    height: Theme.size-medium;
    clip: false;

    states [
        selected when root.is-selected: {
            width: Theme.size-big;
            height: Theme.size-big;
            title-label.font-size: Theme.font-size-medium;
        }
    ]

    animate width {
        duration: Theme.duration-regular;
        easing: ease-in;
    }
    animate height {
        duration: Theme.duration-regular;
        easing: ease-in;
    }
    animate background { duration: Theme.duration-fast; }

    image := Image {
        x: (parent.width - self.width) / 2;
        y: (parent.height - self.height) / 2;
        width: 80%;
        height: 80%;
        colorize: highlight-fg;

        animate colorize { duration: Theme.duration-fast; }
    }

    // Selection text
    title-label := TitleLabel {
        x: (parent.width - self.width) / 2;
        y: parent.height;
        text <=> root.title;
        font-size: Theme.font-size-regular;
        width: 100%;
        wrap: word-wrap;
        color: fg;
    }
}
