// SPDX-FileCopyrightText: 2025 some100 <ootinnyoo@outlook.com>
// SPDX-License-Identifier: MIT

import { TextEdit, LineEdit, StandardButton, Button } from "std-widgets.slint";
import { BootList } from "boot_list.slint";
import { Card } from "card.slint";
import { Theme } from "theme.slint";
import { TitleLabel } from "title_label.slint";
import { Editor } from "editor.slint";

export component Ui inherits Window {
    out property <[{ parser: string, image: image}]> images: [
        { parser: "bls", image: @image-url("icons/linux.png") },
        { parser: "fallback", image: @image-url("icons/fallback.png") },
        { parser: "osx", image: @image-url("icons/osx.png") },
        { parser: "shell", image: @image-url("icons/shell.png") },
        { parser: "uki", image: @image-url("icons/linux.png") },
        { parser: "windows", image: @image-url("icons/windows.png") },
        { parser: "special", image: @image-url("icons/special.png") },
    ];
    out property <[{ label: string, value: string}]> fields: [
        { label: "title", value: "" },
        { label: "version", value: "" },
        { label: "machine_id", value: "" },
        { label: "sort_key", value: "" },
        { label: "options", value: "" },
        { label: "devicetree", value: "" },
        { label: "architecture", value: "" },
        { label: "efi", value: "" },
    ];
    in-out property <int> listIdx;
    in-out property <int> timeout;
    out property <string> error;

    in property <[{ title: string, image: image}]> items;
    in property <color> fg;
    in property <color> bg;
    in property <color> highlight-fg;
    in property <color> highlight-bg;

    callback display-err(err: string);
    display-err(err) => {
        root.error = err;
        error-popup.show();
    }

    callback display-fatal-err(err: string);
    display-fatal-err(err) => {
        root.error = err;
        fatal-popup.show();
    }

    callback fill-fields(fields: [{ label: string, value: string}]);
    fill-fields(fields) => {
        root.fields = fields;
    }

    function close-edit() {
        editor-popup.visible = false;
        editor-bg.visible = false;
    }

    function show-edit() {
        editor-popup.visible = true;
        editor-bg.visible = true;
    }

    pure callback try-boot(idx: int);
    pure callback try-edit(idx: int);
    pure callback save-changes(fields: [{ label: string, value: string}], idx: int);
    pure callback persist-config(idx: int);
    pure callback remove-config(idx: int);

    forward-focus: boot-list;

    default-font-family: Theme.font-family;

    background: bg;

    boot-list := BootList {
        y: (root.height - self.height) / 2;
        height: 100%;
        itemWidth: Theme.size-medium;
        count: root.items.length;
        listIdx <=> root.listIdx;
        spacing: Theme.spacing-medium;
        timeout <=> root.timeout;
        try-boot(int) => {
            root.try-boot(int)
        }
        try-edit(int) => {
            root.try-edit(int)
        }
        close-edit() => {
            root.close-edit()
        }
        show-edit() => {
            root.show-edit()
        }

        for item[index] in root.items: Card {
            is-selected: index == root.listIdx;
            title: item.title;
            image-source: item.image;
            y: (parent.height - self.height) / 2;
            fg: root.fg;
            highlight-bg: root.highlight-bg;
            highlight-fg: root.highlight-fg;
        }
    }

    timeout-label := TitleLabel {
        text: timeout > 0 ? "Booting in \{timeout} seconds" : "";
        x: (root.width - self.width) / 2;
        y: ((root.height - self.height) * (5 / 6));
        font-size: Theme.font-size-medium;
        color: root.fg;
    }

    error-popup := PopupWindow {
        Rectangle {
            background: root.highlight-bg;
            border-radius: Theme.radius-regular;
            error-label := TitleLabel {
                text: "Failed to boot: \{error}.\n\nClick anywhere or press ESC to continue.";
                font-size: Theme.font-size-medium;
                height: 100%;
                width: 100%;
                wrap: word-wrap;
                color: root.highlight-fg;
                vertical-alignment: center;
            }
        }

        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        height: root.height / 4;
        width: root.width / 4;
        close-policy: close-on-click;
    }

    fatal-popup := PopupWindow {
        Rectangle {
            background: root.highlight-bg;
            border-radius: Theme.radius-regular;
            fatal-label := TitleLabel {
                text: "Fatal error occurred: \{error}.\n\nPlease press any key to restart.";
                font-size: Theme.font-size-medium;
                height: 100%;
                width: 100%;
                wrap: word-wrap;
                color: root.highlight-fg;
                vertical-alignment: center;
            }
        }

        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        height: root.height / 4;
        width: root.width / 4;
        close-policy: no-auto-close;
    }

    editor-bg := Rectangle {
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        height: root.height / 2;
        width: root.width / 2;
        background: root.highlight-bg;
        visible: false;
        border-radius: Theme.radius-regular;
    }

    editor-popup := Editor {
        highlight-bg: root.highlight-bg;
        highlight-fg: root.highlight-fg;
        fields <=> root.fields;

        visible: false;
        x: (root.width - self.width) / 2;
        y: (root.height - self.height) / 2;
        height: root.height / 2;
        width: root.width / 2;

        StandardButton {
            kind: close;
            clicked => {
                root.close-edit();
            }
        }

        StandardButton {
            kind: apply;
            clicked => {
                root.save-changes(fields, root.listIdx);
            }
        }

        Button {
            text: "Save Persistent Config to filesystem";
            clicked => {
                root.persist-config(root.listIdx);
            }
            dialog-button-role: action;
        }

        Button {
            text: "Remove Persistent Config from filesystem";
            clicked => {
                root.remove-config(root.listIdx);
            }
            dialog-button-role: action;
        }
    }
}
