// SPDX-FileCopyrightText: 2025 some100 <ootinnyoo@outlook.com>
// SPDX-License-Identifier: MIT

import "fonts/Roboto-Regular.ttf";

export global Theme {
    // durations
    out property <duration> duration-fast: 50ms;
    out property <duration> duration-regular: 100ms;

    // radius
    out property <length> radius-regular: 16px;

    // sizes
    out property <length> size-small: 24px;
    out property <length> size-medium: 128px;
    out property <length> size-big: 170px;

    // spacings
    out property <length> spacing-regular: 4px;
    out property <length> spacing-medium: 8px;

    // typo
    out property <string> font-family: "Roboto";
    out property <length> font-size-regular: 12px;
    out property <length> font-size-medium: 28px;
    out property <int> font-weight-regular: 400;
}
